config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'events#index'
  resources :users, only: %i[index show]
  resources :events
  resources :events, only: %i[index show new create destroy] do
    member do
      post 'attend'
    end
  end
  # get 'events/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :invitations
  has_many :attendees, through: :invitations, source: :user

  scope :past_events, -> { where('date < ?', Date.current) }
  scope :upcoming_events, -> { where('date >= ?', Date.current) }

  def past
    date < Date.current
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = Event.all
    @upcoming = Event.upcoming_events
    @past = Event.past_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      @event.creator = current_user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @upcoming_events = Event.upcoming_events
  end

  def attend
    @event = Event.find_by(id: params[:id])
    Invitation.create!(event_id: @event.id, user_id: current_user.id)
    redirect_to root_path
  end

  # def destroy
  #     @event = Event.find(params[:id])
  #     @event.destroy
  #     redirect_to root_path
  # end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :event_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @upcoming_events = current_user.attended_events.upcoming_events
    @past_events = current_user.attended_events.past_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_options
    if user_signed_in?
      (content_tag :li, class: 'nav-item mx-3' do
        button_to 'Sign out', destroy_user_session_path, redirect_to: root_path, method: :delete,
                                                         class: 'text-decoration-none link-dark'
      end) +
        (content_tag :li, class: 'nav-item mx-3' do
          link_to 'Edit profile', edit_user_registration_path, class: 'text-decoration-none link-dark'
        end) +
        (content_tag :li, class: 'nav-item mx-3' do
          link_to 'New Event', new_event_path, class: 'text-decoration-none link-dark'
        end) +
        (content_tag :li, class: 'nav-item mx-3' do
          link_to 'My Events', user_path(:id), class: 'text-decoration-none link-dark'
        end)

    else
      (content_tag :li, class: 'nav-item mx-3' do
         link_to 'Sign in', new_user_session_path, class: 'text-decoration-none link-dark'
       end) +
        (content_tag :li, class: 'nav-item mx-3' do
          link_to 'Sign up', new_user_registration_path, class: 'text-decoration-none link-dark'
        end)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def attend_event(event)
    return unless user_signed_in? && !event.past

    (button_to 'Attend', attend_event_path(event), method: :post, class: 'btn btn-dark')
  end

  # def delete_event(event)
  #   if current_user == event.creator
  #     (link_to 'Delete', event, confirm: 'Are you sure?', method: :delete)
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> Upcoming Events </h1>
<% @upcoming.each do |event| %>
        <p><%= event.title%> </p>
        <%= link_to 'show', event %>
<%end%>

<h1> Past Events </h1>
<% @past.each do |event| %>
    <p><%= event.title%> </p>
    <%= link_to 'show', event %>
<%end%>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>

    <%= f.label :date %>
    <%= f.date_field :date, class: 'form-control' %>

    <%= f.submit "Create event" %>
<% end %>

app/views/events/show.html.erb
<div>
<p><%= @event.title%> </p>
<p><%= @event.description%> </p>
<p><%= @event.date%> </p>
<p><%= @event.creator.email%> </p>
<%= attend_event(@event) %>
<p> Attendees: </p>
<% @event.attendees.each do |attendee| %>
    <%= attendee.email %> <br> <br/>
<% end %>
</div>

app/views/layouts/_header.html.erb
<%= csrf_meta_tags %>
<nav class="navbar navbar-expand-lg bg-secondary">
  <div class="container-fluid">
    <%= link_to 'Events', events_path, class: 'text-decoration-none link-dark fw-bolder mx-3' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-3">
        <%= user_options %>
      </ul>
    </div>

    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
Upcoming Events:<br/>
  <% @upcoming_events.each do |event| %>
    <%= event.description %> <br/>
  <% end %>
<br/><br/>